### ISSUE TITLE
New project name?

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/system_registry#14]
It is my sincere hope not to start a big bike shedding thread going here, so could we keep this to "I :heart: the name `system_registry`" or "how about calling it xyz" comments? I'm just wondering if there's a better name for this project prior to setting it in stone for 1.0. 

I keep getting Windows 95 vibes from the current name, but I don't have any good suggestions for a better name... I promise to get over my issues if nothing pops up. Feel free to flame me on slack...

**Comment by adkron** [comment]
`system_registry` seems fine to me. You could try `system_directory`, `system_index`, or `system_storage` if you feel like you need something new.

**Comment by mobileoverlord** [comment]
I originally had the Windows vibe, but I got over it. At this point I have started to like it. Not sure I have any alternative name suggestions. I think we should stick it out, especially since it's on hex. It would have to be a really good name for me to be persuaded at this stage.

**Comment by tmecklem** [comment]
Same. Felt like Windows, then it didn't. Now I just load up regedit, change my KVs and life is good. In all seriousness, I'm 👍  with `system_registry` at this point too.

**Comment by GregMefford** [comment]
I was never a big fan of the name, but I think at this point, lots of people are already familiar with it. We've even talked about it from the keynote at ElixirConf, so unless it's something clearly more descriptive of what SystemRegistry is, I think we're committed.

The word "Registry" in SystemRegistry doesn't bother me any more than the `Registry` module in Elixir itself. 🤷‍♂️

**Comment by fhunleth** [comment]
I have two concerns. One is the initial reaction - dealing with Windows Registry jokes is getting old. I know that people aren't serious, but the Windows scars run deep with some people and I hate that coloring feelings towards a library. The second is accuracy and consistency in naming. I'll describe more.

I think that the `system` part is mostly accurate. There is only one instance of the `system_registry` by design. Everything is global - kv pairs are stored in a global container (at least the abstraction makes it look that way). Reports contain global state. I'm not sure that we'll ever allow users to segment their config/status kv pairs between different instances of the `system_registry`. We'd want them to segment their kv pairs in the tree - probably at the root level. 

Regarding `registry`, I've felt that the word "registry" in Elixir and Erlang is always used for kv structures where the value is always a pid. For Nerves stuff, `registry` is inconsistent with the name that we gave to the `Nerves.Runtime` key-value store (`Nerves.Runtime.KV`). Both of these map keys to non-pid terms (the latter may not work for non-String types, but I could see us fixing that). 

Also, there's a pub-sub aspect to this library that's not conveyed in the name.

**Comment by fhunleth** [comment]
From @GregMefford on slack
> I think `Cortex` is my favorite so far, since it just implies both storing information and distributing it to interested parties. And it’s more of a marketing term instead of a “thing”

**Comment by mobileoverlord** [comment]
I feel like the ship has sailed on renaming the lib. If something really really really good pops up, feel free to reopen this issue.
